---
version: '3'

services:
  w1therm:
    image: mafrosis/dht22
    restart: unless-stopped
    build:
      context: .
    environment:
      - DEBUG
      - HA_DEVICE=ringil
      - HA_SENSOR_NAME=Server Closet
      - MQTT_HOST=192.168.1.198
      - MQTT_TOPIC_ROOM
    volumes:
      - ./w1therm.py:/srv/app/w1therm.py
